INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (1, 'Дизайн помещений', 8);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (2, 'Архитектурное проектирование', 8);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (3, 'Согласование строительных работ', 8);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (4, 'Перепланировка', 8);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (5, 'Монтаж электропроводки', 9);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (6, 'Монтаж электрического "теплого пола"', 9);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (7, 'Установка светильников, розеток, выключателей', 9);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (8, 'Установка охранной сигнализации', 10);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (9, 'Установка видеонаблюдения', 9);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (10, 'Установка системы контроля доступа', 10);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (11, 'Системы автоматизации. "Умный дом"', 10);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (12, 'Ремонт под "ключ"', 7);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (13, 'Шпаклевочные работы', 7);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (14, 'Плиточные и облицовочные работы', 7);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (15, 'Монтаж и устройство потолков', 7);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (16, 'Монтаж ворот, заборов, ролетов', 1);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (17, 'Монтаж систем вентиляции', 12);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (18, 'Проектирование систем кондиционирования и вентиляции', 12);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (19, 'Монтаж систем кондиционирования', 12);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (20, 'Монтаж водопровода, канализации в помещении', 11);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (21, 'Установка и подключение сантехники', 11);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (22, 'Установка окон, дверей. Остекление балконов', 7);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (23, 'Бурение и устройство скважин', 11);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (24, 'Наружний монтаж водопровада, канализации', 11);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (25, 'Установка систем фильтрации воды', 11);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (26, 'Септик. Системы автономной канализации', 11);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (27, 'Штукатурные работы', 7);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (28, 'Прочистка канализации', 11);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (29, 'Декоративная штукатурка', 7);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (30, 'Работа с гипсокартоном', 7);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (31, 'Укладка, настил полов. Стяжка пола', 7);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (32, 'Ландшафтный дизайн', 6);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (33, 'Малярные работы', 7);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (34, 'Декоративные водопады, водоемы. Фонтаны', 6);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (35, 'Отделка балконов', 7);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (36, 'Детские площадки', 6);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (37, 'Услуги по уходу за участком', 6);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (38, 'Художественная роспись. Фрески', 7);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (39, 'Озеленение', 6);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (40, 'Укладка тротуарной плитки, дорожек', 6);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (41, 'Автоматический полив', 6);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (42, 'Монтаж и строительство бассейнов', 6);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (43, 'Мелкий бытовой ремонт', 13);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (44, 'Газоснабжение', 3);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (45, 'Прокладка и монтаж систем отопления', 3);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (46, 'Обслуживание, ремонт отопления', 3);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (47, 'Система теплотрасс', 3);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (48, 'Проектирование отопления', 3);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (49, 'Монтаж котельного оборудования', 3);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (50, 'Монтаж и устройство водяных "теплых полов"', 3);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (51, 'Аренда строительной техники', 2);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (52, 'Аренда спецтехники', 2);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (53, 'Аренда строительного инструмента', 2);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (54, 'Аренда строительного оборудования', 2);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (55, 'Аренда опалубки', 2);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (56, 'Строительство домов, коттеджей, дач под "ключ"', 1);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (57, 'Строительство каркасных домов', 1);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (58, 'Промышленные, торговые здания и сооружения', 1);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (59, 'Строительство домов из блоков и кирпича', 1);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (60, 'Строительство деревянных домов и срубов', 1);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (61, 'Строительство беседок', 1);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (62, 'Кровельные работы', 1);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (63, 'Кладка кирпича,стеновых блоков и плит', 1);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (64, 'Устройство фундамента. Работы с бетоном', 1);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (65, 'Сварочные работы', 1);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (66, 'Камины. Печи. Дымоходы', 1);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (67, 'Строительство бани, сауны', 1);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (68, 'Фасадные работы', 1);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (69, 'Алмазное сверление. Резка. Демонтажные работы', 1);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (70, 'Изоляционные работы', 1);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (71, 'Монтаж и отделка лестниц', 1);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (72, 'Работа с металлом. Ковка', 1);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (73, 'Строительство бассейнов', 1);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (74, 'Уборка помещений', 4);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (75, 'Вывоз строительного мусора', 4);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (76, 'Мойка фасадов', 4);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (77, 'Аренда инструмента и оборудования', 4);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (78, 'Установка пожарной сигнализации', 10);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (79, 'Видеонаблюдение', 10);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (80, 'Техническое обследование зданий', 8);
INSERT INTO `remont_worktype` (`id`, `name`, `category_id`) VALUES (81, 'Облицовка панелями', 7);
