INSERT INTO `remont_workcategory` (`id`, `name`, `icon`) VALUES (1, 'Строительство. Монтажные работы', 'icons/113.png');
INSERT INTO `remont_workcategory` (`id`, `name`, `icon`) VALUES (2, 'Аренда строительной техники и оборудования', 'icons/110.png');
INSERT INTO `remont_workcategory` (`id`, `name`, `icon`) VALUES (3, 'Отопление. Газоснабжение', 'icons/110_UK7Q0UH.png');
INSERT INTO `remont_workcategory` (`id`, `name`, `icon`) VALUES (4, 'Клининговые услуги', 'icons/110_21UV6V3.png');
INSERT INTO `remont_workcategory` (`id`, `name`, `icon`) VALUES (6, 'Ландшафт, благоустройство территории', 'icons/110_FUoOrH1.png');
INSERT INTO `remont_workcategory` (`id`, `name`, `icon`) VALUES (7, 'Ремонтные и отделочные работы', 'icons/110_QTWnhxV.png');
INSERT INTO `remont_workcategory` (`id`, `name`, `icon`) VALUES (8, 'Архитектура. Дизайн. Проектирование. Оценка', 'icons/110_Q5aW7hw.png');
INSERT INTO `remont_workcategory` (`id`, `name`, `icon`) VALUES (9, 'Электромонтажные работы', 'icons/110_QaDj7UO.png');
INSERT INTO `remont_workcategory` (`id`, `name`, `icon`) VALUES (10, 'Монтаж охранных систем. Видеонаблюдение', 'icons/110_0K0Pct0.png');
INSERT INTO `remont_workcategory` (`id`, `name`, `icon`) VALUES (11, 'Сантехнические работы', 'icons/110_jxc0xUH.png');
INSERT INTO `remont_workcategory` (`id`, `name`, `icon`) VALUES (12, 'Вентиляция. Кондиционирование', 'icons/110_o8Ug6xn.png');
INSERT INTO `remont_workcategory` (`id`, `name`, `icon`) VALUES (13, 'Мелкий бытовой ремонт. "Муж на час"', 'icons/110_ZhjG6fD.png');
